# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '读源码-SDWebImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 读源码-SDWebImage
pod 'SDWebImage'
pod 'YYKit'
pod 'AFNetworking'
end
