# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '读源码-SDWebImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 读源码-SDWebImage
pod 'SDWebImage'
pod 'YYCache'
pod 'YYModel'
pod 'AFNetworking'
end


target 'video_frame' do

pod 'SDWebImage'
end

target 'test' do

pod 'YYCache'
pod 'YYModel'

end